services:
  server:
    image: nodejspro-nest-server:dev
    build:
      context: .
      target: deps
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - '127.0.0.1:3000:3000'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 300M
    volumes:
      - .:/app
      - /app/node_modules
